version: "3.8"

services:
  orders-service:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3000
      - JWT_SECRET=dev-secret-key
      - NODE_ENV=development
      - OTEL_SERVICE_NAME=orders-service
      - OTEL_SERVICE_VERSION=1.0.0
    command: npm run start:dev

  # Example message broker for event publishing (optional)
  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   environment:
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   ports:
  #     - "9092:9092"
  #   depends_on:
  #     - zookeeper

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
