name: crm-service
version: 1.0.0
owner: team-crm
api: ./openapi.yaml
events: ./asyncapi.yaml
auth:
  required_scopes:
    - vendors.read
    - vendors.write
    - catalog.read
    - catalog.write
    - users.read
    - users.write
    - entitlements.read
    - entitlements.write
