name = "crm-service"
main = "dist/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Environment variables (set these in Cloudflare dashboard or use wrangler secret)
[vars]
NODE_ENV = "development"
PORT = "8787"

# Secrets to be set with: wrangler secret put <name>
# - JWT_SECRET
# - DATABASE_URL (for production Turso database)

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "crm-service-db"
database_id = ""  # Will be set after creating database
migrations_dir = "./drizzle"

# Cron triggers for background task processing
[triggers]
crons = ["*/5 * * * *"]  # Run every 5 minutes

[build]
command = "npx tsc -p tsconfig.worker.json"

# Development configuration
[env.development]
vars = { NODE_ENV = "development" }

# Production configuration  
[env.production]
vars = { NODE_ENV = "production" }

# Limits
[limits]
cpu_ms = 50000