name = "podcast-service"
main = "dist/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Environment variables (set these in Cloudflare dashboard or use wrangler secret)
[vars]
NODE_ENV = "development"
PORT = "8787"

# Secrets to be set with: wrangler secret put <name>
# - JWT_SECRET
# - DATABASE_URL (for production Turso database)
# - R2_ACCESS_KEY_ID (for R2 pre-signed URLs)
# - R2_SECRET_ACCESS_KEY (for R2 pre-signed URLs)

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "podcast-service-db"
database_id = "a27b543a-696d-4726-9329-2a15578ac861"
migrations_dir = "./drizzle"

# R2 Storage binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "podcast-service-assets"

[build]
command = "tsc -p tsconfig.worker.json"

# Development configuration
[env.development]
vars = { NODE_ENV = "development" }

# Production configuration  
[env.production]
vars = { NODE_ENV = "production" }

# Limits
[limits]
cpu_ms = 50000
